### PR TITLE
added script to automate library dependency download

### PR DESCRIPTION
**Pull request by faradaym**
Adds a python script for automated installing of the library dependencies for basic Mama and Papa ducks.

### CODE REVIEW

**Comment by faradaym** [comment]
Could someone test this on windows for me? Thanks

**Comment by TrevorCE** [comment]
Hey, I ran the script on Windows. Is this the result I should expect? 
image

**Comment by faradaym** [comment]
@TrevorCE Yep, if you are able to compile a Mama or Papa sketch then it should be good

**Comment by TrevorCE** [comment]
@faradaym I successfully compiled a Mama, everything worked as expected!

**Review by tqrahman — APPROVED** [review]

**Pull request merged**
