### PR TITLE
Heltec v3 support

### PR DESCRIPTION
**Pull request by BrentonPoke**
**Describe at a high level the solution you're providing**
Adding definition for HeltecV3 board along with new IRQ handling to make board fully functional

**Is this a patch, a minor version change, or a major version change**
Patch.

**Is this related to an open issue?**
No open issue

**Additional context**
Was tested with 2 HeltecV3 boards, one transmitting straight to the other using the same branch code.

### CODE REVIEW

**Comment by hawk4031** [comment]
Can you add the same change you made in `library.json` to `library.properties` for RadioLib? We need to do our best to keep these two files in sync with each other.

**Comment by scottbob09** [comment]
Sorry to spam the list.   But.  Is there a version of clusterduck that
actually compiles?  Or perhaps binary files?  Because if we are all using
the same hardware, why not?

**Comment by BrentonPoke** [comment]
> Sorry to spam the list. But. Is there a version of clusterduck that actually compiles? Or perhaps binary files? Because if we are all using the same hardware, why not?

It does compile, but you will have problems with ArduinoIDE. I suggest you use [platformio](https://platformio.org/install/integration) and use this config:

```
[env:heltec_wifi_lora_32_V3]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200
monitor_filters = time
upload_port = <the port your board is on>
lib_deps =
	Update
	ArduinoOTA
	contrem/arduino-timer @ ^2.3.0
	knolleary/PubSubClient@^2.8
	paulstoffregen/Time@^1.6.1
	https://github.com/me-no-dev/ESPAsyncWebServer.git
	https://github.com/BrentonPoke/ClusterDuck-Protocol.git#heltec-v3
```

**Comment by tqrahman** [comment]
I just uploaded to the Heltec v3 and it works! 

The next step is to check to see if uploading to RadioLib 6.1^ will support the older boards.

**Comment by faradaym** [comment]
I tried this PR on a Heltec v2 and a T-Beam using RadioLib 6.1.0, and they were able to communicate!

We will need to change the versions to download with the automator script in `/cdp-dependency-automator-script/dependencies.json` as well

I checked what would happen with one of them on RadioLib v5.6 and the other v6.1, and this was output when sending messages

`INF: DuckRadio.cpp]  Interrupt flag was set: packet reception complete`
`[INF: DuckRadio.cpp]  Interrupt flag was set: valid header received`
`[INF: DuckRadio.cpp]  Interrupt flag was set: 126X payload CRC error`
`[INF: MamaDuck.cpp]  ====> handleReceivedPacket: START`
`[INF: DuckRadio.cpp]  readReceivedData() - packet length returns: 37`
`[INF: DuckRadio.cpp]  readReceivedData() - lora.readData returns: -24`
`[ERR: DuckRadio.cpp:150]  ERROR  readReceivedData failed. err: -24`
`[ERR: MamaDuck.cpp:74]  ERROR failed to get data from DuckRadio. rc = -1050`

**Comment by BrentonPoke** [comment]
> I tried this PR on a Heltec v2 and a T-Beam using RadioLib 6.1.0, and they were able to communicate!
> 
> We will need to change the versions to download with the automator script in `/cdp-dependency-automator-script/dependencies.json` as well
> 
> I checked what would happen with one of them on RadioLib v5.6 and the other v6.1, and this was output when sending messages
> 
> `INF: DuckRadio.cpp] Interrupt flag was set: packet reception complete` `[INF: DuckRadio.cpp] Interrupt flag was set: valid header received` `[INF: DuckRadio.cpp] Interrupt flag was set: 126X payload CRC error` `[INF: MamaDuck.cpp] ====> handleReceivedPacket: START` `[INF: DuckRadio.cpp] readReceivedData() - packet length returns: 37` `[INF: DuckRadio.cpp] readReceivedData() - lora.readData returns: -24` `[ERR: DuckRadio.cpp:150] ERROR readReceivedData failed. err: -24` `[ERR: MamaDuck.cpp:74] ERROR failed to get data from DuckRadio. rc = -1050`

Which one was on 5.6?

**Comment by faradaym** [comment]
@BrentonPoke I just tested again, with 6.1.0 on T-Beam I get the error in the serial receiving from 5.6.0 Heltec v2. The 5.6 Heltec does not error. When the Heltec has 6.1 it errors when receiving from 5.6 T-Beam. When both are on the same version, there are no errors.

**Comment by BrentonPoke** [comment]
> @BrentonPoke I just tested again, with 6.1.0 on T-Beam I get the error in the serial receiving from 5.6.0 Heltec v2. The 5.6 Heltec does not error. When the Heltec has 6.1 it errors when receiving from 5.6 T-Beam. When both are on the same version, there are no errors.

So if you're compiling this branch using RadioLib 5.6, there should be errors because 5.6 does not have the 126X IRQ flags like `RADIOLIB_SX126X_CMD_CLEAR_IRQ_STATUS` . This branch must be compiled with 6.1.x and any old ducks would have to be updated to this code.

**Comment by tqrahman** [comment]
I was able to transmit data using heltec v3 and receive data in a v2; Ravyn confirmed it worked on v2's. Brenton confirmed on T-beams. I will merge this PR!

Few things to note:

- Heltec v3 has the new LoRa 126X chip so for it to work, CDP needs to update RadioLib to 6.1.

- For those who are using Heltec v3's, you need to use PlatformIO to upload the firmware. At the moment, Arduino does not support v3 yet since it is fairly new.

**Pull request merged**
