### PR TITLE
Add Acking for Public and Private Chats

### PR DESCRIPTION
**Pull request by faradaym**
**Describe at a high level the solution you're providing**
Added feature to ack chat messages and resend messages that have not been acked in a certain period of time. There is an option in the control panel to disable the ack feature.

**Is this a patch, a minor version change, or a major version change**
new feature

**Fixes**
fixes message age bug on sent messages, mentioned here: https://github.com/Call-for-Code/ClusterDuck-Protocol/pull/279#issue-1227824934

### CODE REVIEW

**Comment by faradaym** [comment]
Yes, it fixes a bug that is still present in master and adds a feature that Nick requested. I will try to fix the sign off.

**Comment by TimoWielink** [comment]
Do you think this will impact any work from #299

**Review by TimoWielink — COMMENTED** [review]
If you can also update the version number on this on that would be great

in the readme, library.json and duck utils

**Comment by faradaym** [comment]
> Do you think this will impact any work from #299

I don't believe it will have an effect on that PR

**Review by TimoWielink — COMMENTED** [review]
Tested and fixed merge conflicts

**Review by TimoWielink — APPROVED** [review]

**Pull request merged**
