### PR TITLE
WIP OO

### PR DESCRIPTION
**Pull request by Salzi**
This is the first object oriented version of the cdp.

### CODE REVIEW

**Comment by krook** [comment]
In general, I like the approach. Do you have a commit to fix the conflict @Salzi? I couldn't quite see exactly what it was.

**Comment by Salzi** [comment]
@krook Should work now. And just to be clear: It's currently still WIP because I need someone from the team to document the missing parameters (check all `TODO` entries)

**Comment by krook** [comment]
> I need someone from the team to document the missing parameters (check all TODO entries)

Got it. Thanks.

**Comment by Salzi** [comment]
This Pull Request is now much too far away from master to merge. I'm closing it for this. If then one day you want to go in the direction of object orientation, you can use this PR as a reference. But the whole work has to be done again. It is then important that no other major changes are made before the new PR is merged.

**Pull request closed without merging**
