### PR TITLE
How to build a duck as markdown

### LINKED ISSUE #10: add source for generating the pdf
**Is your feature request related to a problem? Please describe.**
Would like to help update the info in the .pdf, but do not know where the source for it is. Can that be shared? 

**Describe the solution you'd like**
The "source" for the pdf to be shared so it can be updated. (even if it is a word doc or something like that)

**Describe alternatives you've considered**
The pdf may be able to be generated from doxygen/sphinx or other toolings.

**Additional context**
Just want to help improve this cool project. :-)

### PR DESCRIPTION
**Pull request by Salzi**
Add the how to build a duck as markdown and add a github workflow to build the PDF.

Should fix  #10

### CODE REVIEW

**Comment by TimoWielink** [comment]
Testing Pandoc Locally before merge

**Comment by krook** [comment]
Beautiful. One issue I see is that each of the image captions just says `alt_text`

**Comment by Salzi** [comment]
replaced all the `alt_text``but I also disabled the figure caption because they are also disabled in the current documentation.

**Comment by krook** [comment]
Thanks @Salzi. @TimoWielink what do you think of the latest?

**Comment by krook** [comment]
Today I learned how to use GitHub Actions. This is great. Nice work @Salzi

**Comment by TimoWielink** [comment]
- Checked if the PDf gets generated correctly
- Checked file structure
- Images are all placed correctly 

Great work @Salzi

**Pull request merged**
